# Description:
#   The configuration file for training the NN model to detect two classes of objects:
#     1. INTEMAC_Logo_Yellow
#     2. INTEMAC_Logo_Blue
#   The dataset is organized into training, validation, and testing partitions.

# The absolute path to the main directory of the dataset.
path: '/absolute/path/to/Dataset_v1'

# Paths to the specific partitions (train, validation, test) that contain the dataset images and labels.
train: 'images/train'
val: 'images/valid'
test: 'images/test'

# Parameters:
#   The total number of classes in the dataset.
nc: 2

# List of class names.
names: ['INTEMAC_Logo_Yellow', 'INTEMAC_Logo_Blue']